### ISSUE TITLE
Sliding hockey puck leaves sale pixels on mobile

### ISSUE THREAD

**Issue by SRM256** [jpeterbaker/bga_homeworlds#3]
See image. When the hockey puck for whose turn it is slides on my iPhone, it leaves lines behind it. These lines go away when invalidating the screen. Only observed on mobile. I'd suggest it was fine to show acceleration, but the lines are the inverse of the usual motion blur lines, so it just looks confusing. 
![bug](https://user-images.githubusercontent.com/4238447/174448602-1aa2dc52-b47a-4178-b844-6004baae0021.png)

**Comment by jpeterbaker** [comment]
@SRM256 ~~This is a little hard for me to address since it doesn't happen on any of my devices. Are you using Safari for mobile?~~

EDIT: Looks like this happens in Safari for MacOS as well.

FYI, my tentative plan is to remove the glow during the slide, but only for browsers that have this problem since the token looks weird without the glow (the border blends into the background).

**Comment by jpeterbaker** [comment]
I think I've got this fixed. Let me know if you see it again.
